spring.application.name=sudconnect-core

# postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/sudconnect
spring.datasource.username=sudconnect
spring.datasource.password=sudconnect
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa/hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.default-schema=public

logging.level.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG